# Generated by Django 2.0.4 on 2018-05-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applist',
            name='package_version_code',
            field=models.FloatField(),
        ),
    ]
